/*EK-TM4C123GXL_LIB
 * 作者:RATTAN
 * 文件描述:none
 */

#define CLOCK_XTAL_PLL_80M SYSCTL_SYSDIV_2_5
#define CLOCK_XTAL_PLL_40M SYSCTL_SYSDIV_5
#define CLOCK_XTAL_PLL_20M SYSCTL_SYSDIV_10
#define CLOCK_XTAL_PLL_10M SYSCTL_SYSDIV_20
#define CLOCK_XTAL_PLL_5M  SYSCTL_SYSDIV_40

